# This is a basic workflow to help you get started with Actions

name: Debug workflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  pull_request:
    branches: [ master ]
    types: [ closed ]
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Checkout
        uses: actions/checkout@v2.3.3

      - name: Set up our JDK environment
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 11
          
      - name: Build
        id: buildAllApks
        uses: eskatos/gradle-command-action@v1.3.3
        with:
          gradle-version: current
          wrapper-cache-enabled: true
          dependencies-cache-enabled: true
          configuration-cache-enabled: true
          arguments: assembleDebug
          
      - name: Run Kotlin Linter
        run: ./gradlew ktlint

      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest
        
      - name: Sign artifact
        if: false == contains(github.event.head_commit.message, '[norelease]')
        id: signArtifact
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/apk/debug
          alias: ${{ secrets.KEY_ALIAS }}
          signingKeyBase64: ${{ secrets.DEBUG_KEY_BASE64 }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        
      - name: just echo a message
        run: |
          echo "Hello ${{ steps.signArtifact.outputs.signedReleaseFile }}"
        
      - name: Create release
        id: release
        uses: rymndhng/release-on-push-action@master
        with:
          bump_version_scheme: minor
          tag_prefix: debug-v
      
      - name: Upload binaries to release
        if: false == contains(github.event.head_commit.message, '[norelease]')
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ steps.signArtifact.outputs.signedReleaseFile }}
          asset_name: app_adidas_${{ steps.release.outputs.version }}.apk
          tag: ${{ steps.release.outputs.version }}
          overwrite: true
          body: "Test debug"
